

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChartModelV2{
/*
{
  "count": 2,
  "mood": "Hứng khởi"
} 
*/

  int? count;
  String? mood;

  ChartModelV2({
    this.count,
    this.mood,
  });
  ChartModelV2.fromJson(Map<String, dynamic> json) {
    count = json['count']?.toInt();
    mood = json['mood']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['count'] = count;
    data['mood'] = mood;
    return data;
  }
}

class ChartModel {
/*
{
  "Jan": [
    {
      "count": 2,
      "mood": "Hứng khởi"
    }
  ]
} 
*/

  List<ChartModelV2?>? Jan;

  ChartModel({
    this.Jan,
  });
  ChartModel.fromJson(Map<String, dynamic> json) {
    if (json['Jan'] != null) {
      final v = json['Jan'];
      final arr0 = <ChartModelV2>[];
      v.forEach((v) {
        arr0.add(ChartModelV2.fromJson(v));
      });
      Jan = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (Jan != null) {
      final v = Jan;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Jan'] = arr0;
    }
    return data;
  }
}
