///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommentModel {
/*
{
  "id": 1,
  "comment": "Đỉnh kout",
  "diaryId": 25,
  "createdAt": "2023-11-21T22:26:28.776",
  "createdBy": "22",
  "nickName": "Kamen Rider",
  "avatar": "string"
}
*/

  int? id;
  String? comment;
  int? diaryId;
  String? createdAt;
  String? createdBy;
  String? nickName;
  String? avatar;

  CommentModel({
    this.id,
    this.comment,
    this.diaryId,
    this.createdAt,
    this.createdBy,
    this.nickName,
    this.avatar,
  });
  CommentModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    comment = json['comment']?.toString();
    diaryId = json['diaryId']?.toInt();
    createdAt = json['createdAt']?.toString();
    createdBy = json['createdBy']?.toString();
    nickName = json['nickName']?.toString();
    avatar = json['avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['comment'] = comment;
    data['diaryId'] = diaryId;
    data['createdAt'] = createdAt;
    data['createdBy'] = createdBy;
    data['nickName'] = nickName;
    data['avatar'] = avatar;
    return data;
  }
}
