///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateDiaryModel {
/*
{
  "change": "string",
  "happened": "Em đã yêu một người có ước mơ, mơ điều làm em thấy hoang mang lo sợ.Sợ yêu một người không phải, như em đã từng.Nếu như anh đi về phía đó, liệu rằng anh có còn thấy em. Lệ trong đôi mắt sao mà lỡ đi ánh nắng mặt trời",
  "moodId": 2,
  "other": "string",
  "place": "string",
  "status": "PUBLIC",
  "thinkingFelt": "string",
  "thinkingMoment": "string",
  "thinkingNow": "good good bad",
  "time": "2023-11-08T10:06:08.087Z",
  "title": "string"
}
*/

  String? change;
  String? happened;
  int? moodId;
  String? other;
  String? place;
  String? status;
  String? thinkingFelt;
  String? thinkingMoment;
  String? thinkingNow;
  String? time;
  String? title;

  CreateDiaryModel({
    this.change,
    this.happened,
    this.moodId,
    this.other,
    this.place,
    this.status,
    this.thinkingFelt,
    this.thinkingMoment,
    this.thinkingNow,
    this.time,
    this.title,
  });
  CreateDiaryModel.fromJson(Map<String, dynamic> json) {
    change = json['change']?.toString();
    happened = json['happened']?.toString();
    moodId = json['moodId']?.toInt();
    other = json['other']?.toString();
    place = json['place']?.toString();
    status = json['status']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    thinkingNow = json['thinkingNow']?.toString();
    time = json['time']?.toString();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['change'] = change;
    data['happened'] = happened;
    data['moodId'] = moodId;
    data['other'] = other;
    data['place'] = place;
    data['status'] = status;
    data['thinkingFelt'] = thinkingFelt;
    data['thinkingMoment'] = thinkingMoment;
    data['thinkingNow'] = thinkingNow;
    data['time'] = time;
    data['title'] = title;
    return data;
  }
}
