///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateDiary {
/*
{
  "change": "string",
  "happened": "đang rất căng thẳng",
  "moodId": 1,
  "other": "string",
  "place": "string",
  "thinkingFelt": "bất lực",
  "thinkingMoment": "vẫn bất lực",
  "thinkingNow": "sắp tuyệt vọng",
  "time": "2023-11-04T13:58:49.627Z",
  "title": "string"
}
*/

  String? change;
  String? happened;
  int? moodId;
  String? other;
  String? place;
  String? thinkingFelt;
  String? thinkingMoment;
  String? thinkingNow;
  String? time;
  String? title;

  CreateDiary({
    this.change,
    this.happened,
    this.moodId,
    this.other,
    this.place,
    this.thinkingFelt,
    this.thinkingMoment,
    this.thinkingNow,
    this.time,
    this.title,
  });
  CreateDiary.fromJson(Map<String, dynamic> json) {
    change = json['change']?.toString();
    happened = json['happened']?.toString();
    moodId = json['moodId']?.toInt();
    other = json['other']?.toString();
    place = json['place']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    thinkingNow = json['thinkingNow']?.toString();
    time = json['time']?.toString();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['change'] = change;
    data['happened'] = happened;
    data['moodId'] = moodId;
    data['other'] = other;
    data['place'] = place;
    data['thinkingFelt'] = thinkingFelt;
    data['thinkingMoment'] = thinkingMoment;
    data['thinkingNow'] = thinkingNow;
    data['time'] = time;
    data['title'] = title;
    return data;
  }
}
