///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllDiaryPublicModel {
/*
{
  "id": 17,
  "title": "string",
  "mood": "hạnh phúc",
  "happened": "string",
  "thinkingMoment": "string",
  "time": "2023-11-08T09:18:10.149",
  "place": "string",
  "thinkingNow": "string",
  "thinkingFelt": "string",
  "change": "string",
  "other": "string",
  "status": "PUBLIC",
  "createdBy": "1",
  "createdAt": "2023-11-08T16:18:38.502",
  "nickname": "mohamed Salah",
  "avatar": "string"
}
*/

  int? id;
  String? title;
  String? mood;
  String? happened;
  String? thinkingMoment;
  String? time;
  String? place;
  String? thinkingNow;
  String? thinkingFelt;
  String? change;
  String? other;
  String? status;
  String? createdBy;
  String? createdAt;
  String? nickname;
  String? avatar;

  GetAllDiaryPublicModel({
    this.id,
    this.title,
    this.mood,
    this.happened,
    this.thinkingMoment,
    this.time,
    this.place,
    this.thinkingNow,
    this.thinkingFelt,
    this.change,
    this.other,
    this.status,
    this.createdBy,
    this.createdAt,
    this.nickname,
    this.avatar,
  });
  GetAllDiaryPublicModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    mood = json['mood']?.toString();
    happened = json['happened']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    time = json['time']?.toString();
    place = json['place']?.toString();
    thinkingNow = json['thinkingNow']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    change = json['change']?.toString();
    other = json['other']?.toString();
    status = json['status']?.toString();
    createdBy = json['createdBy']?.toString();
    createdAt = json['createdAt']?.toString();
    nickname = json['nickname']?.toString();
    avatar = json['avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['mood'] = mood;
    data['happened'] = happened;
    data['thinkingMoment'] = thinkingMoment;
    data['time'] = time;
    data['place'] = place;
    data['thinkingNow'] = thinkingNow;
    data['thinkingFelt'] = thinkingFelt;
    data['change'] = change;
    data['other'] = other;
    data['status'] = status;
    data['createdBy'] = createdBy;
    data['createdAt'] = createdAt;
    data['nickname'] = nickname;
    data['avatar'] = avatar;
    return data;
  }
}
