///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllDiaryModel {
/*
{
  "id": 3,
  "title": "string",
  "happened": "string",
  "thinkingMoment": "string",
  "time": "2023-10-09T20:27:52",
  "place": "asfa",
  "thinkingNow": "string",
  "thinkingFelt": "f",
  "change": "string",
  "other": "string",
  "createdAt": "2023-10-10T03:35:44",
  "createdBy": 1,
  "comments": [
    null
  ],
  "status": "PUBLIC"
}
*/

  int? id;
  String? title;
  String? happened;
  String? thinkingMoment;
  String? time;
  String? place;
  String? thinkingNow;
  String? thinkingFelt;
  String? change;
  String? other;
  String? createdAt;
  String? createdBy;
  List<GetAllDiaryCommentsModel?>? comments;
  String? status;

  GetAllDiaryModel({
    this.id,
    this.title,
    this.happened,
    this.thinkingMoment,
    this.time,
    this.place,
    this.thinkingNow,
    this.thinkingFelt,
    this.change,
    this.other,
    this.createdAt,
    this.createdBy,
    this.comments,
    this.status,
  });
  GetAllDiaryModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    happened = json['happened']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    time = json['time']?.toString();
    place = json['place']?.toString();
    thinkingNow = json['thinkingNow']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    change = json['change']?.toString();
    other = json['other']?.toString();
    createdAt = json['createdAt']?.toString();
    createdBy = json['createdBy']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['happened'] = happened;
    data['thinkingMoment'] = thinkingMoment;
    data['time'] = time;
    data['place'] = place;
    data['thinkingNow'] = thinkingNow;
    data['thinkingFelt'] = thinkingFelt;
    data['change'] = change;
    data['other'] = other;
    data['createdAt'] = createdAt;
    data['createdBy'] = createdBy;
    data['status'] = status;
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllDiaryCommentsModel {
/*
{
  "id": 20,
  "comment": "10 điểm em ei",
  "diaryId": 12,
  "createdAt": "2023-11-04T21:41:49.935",
  "createdBy": "1",
  "nickName": "string",
  "avatar": "string"
}
*/

  int? id;
  String? comment;
  int? diaryId;
  String? createdAt;
  String? createdBy;
  String? nickName;
  String? avatar;

  GetAllDiaryCommentsModel({
    this.id,
    this.comment,
    this.diaryId,
    this.createdAt,
    this.createdBy,
    this.nickName,
    this.avatar,
  });
  GetAllDiaryCommentsModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    comment = json['comment']?.toString();
    diaryId = json['diaryId']?.toInt();
    createdAt = json['createdAt']?.toString();
    createdBy = json['createdBy']?.toString();
    nickName = json['nickName']?.toString();
    avatar = json['avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['comment'] = comment;
    data['diaryId'] = diaryId;
    data['createdAt'] = createdAt;
    data['createdBy'] = createdBy;
    data['nickName'] = nickName;
    data['avatar'] = avatar;
    return data;
  }
}

