///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAllDiaryPublicModel {
/*
{
  "id": 12,
  "title": "string",
  "mood": "Vui vẻ",
  "happened": "1 phút lỡ lời cả đời lỡ duyên",
  "thinkingMoment": "oaaoiio",
  "time": null,
  "date": null,
  "place": "uauuaua",
  "level": null,
  "thinkingFelt": "oaoaoaoa",
  "other": "ngày 11-12, lúc 10h",
  "status": "PUBLIC",
  "createdBy": "5",
  "createdAt": "2023-12-12T17:10:23.123356",
  "nickname": "string",
  "avatar": "https://i.imgur.com/F5qIESn.png"
}
*/

  int? id;
  String? title;
  String? mood;
  String? happened;
  String? thinkingMoment;
  String? time;
  String? date;
  String? place;
  String? level;
  String? thinkingFelt;
  String? other;
  String? status;
  String? createdBy;
  String? createdAt;
  String? nickname;
  String? avatar;

  GetAllDiaryPublicModel({
    this.id,
    this.title,
    this.mood,
    this.happened,
    this.thinkingMoment,
    this.time,
    this.date,
    this.place,
    this.level,
    this.thinkingFelt,
    this.other,
    this.status,
    this.createdBy,
    this.createdAt,
    this.nickname,
    this.avatar,
  });
  GetAllDiaryPublicModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    mood = json['mood']?.toString();
    happened = json['happened']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    time = json['time']?.toString();
    date = json['date']?.toString();
    place = json['place']?.toString();
    level = json['level']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    other = json['other']?.toString();
    status = json['status']?.toString();
    createdBy = json['createdBy']?.toString();
    createdAt = json['createdAt']?.toString();
    nickname = json['nickname']?.toString();
    avatar = json['avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['mood'] = mood;
    data['happened'] = happened;
    data['thinkingMoment'] = thinkingMoment;
    data['time'] = time;
    data['date'] = date;
    data['place'] = place;
    data['level'] = level;
    data['thinkingFelt'] = thinkingFelt;
    data['other'] = other;
    data['status'] = status;
    data['createdBy'] = createdBy;
    data['createdAt'] = createdAt;
    data['nickname'] = nickname;
    data['avatar'] = avatar;
    return data;
  }
}
