///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MoodModel {

  String? createdAt;
  String? createdBy;
  int? id;
  String? mood;
  String? status;
  String? description;

  MoodModel({
    this.createdAt,
    this.createdBy,
    this.id,
    this.mood,
    this.status,
    this.description,
  });
  MoodModel.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    createdBy = json['createdBy']?.toString();
    id = json['id']?.toInt();
    mood = json['mood']?.toString();
    status = json['status']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['createdBy'] = createdBy;
    data['id'] = id;
    data['mood'] = mood;
    data['status'] = status;
    data['description'] = description;
    return data;
  }
}


class MoodMusic {
  int? id;
  String? moodSound;
  String? status;

  MoodMusic({
    this.id,
    this.moodSound,
    this.status,
  });
  MoodMusic.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    moodSound = json['moodSound']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['moodSound'] = moodSound;
    data['status'] = status;
    return data;
  }
}
