///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MoodModel {
/*
{
  "createdAt": null,
  "createdBy": null,
  "id": 6,
  "mood": "lú lẫn",
  "status": null,
  "description": null
}
*/

  String? createdAt;
  String? createdBy;
  int? id;
  String? mood;
  String? status;
  String? description;

  MoodModel({
    this.createdAt,
    this.createdBy,
    this.id,
    this.mood,
    this.status,
    this.description,
  });
  MoodModel.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    createdBy = json['createdBy']?.toString();
    id = json['id']?.toInt();
    mood = json['mood']?.toString();
    status = json['status']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['createdBy'] = createdBy;
    data['id'] = id;
    data['mood'] = mood;
    data['status'] = status;
    data['description'] = description;
    return data;
  }
}
