///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InforUserRole {
/*
{
  "id": 2,
  "name": "USER"
}
*/

  int? id;
  String? name;

  InforUserRole({
    this.id,
    this.name,
  });
  InforUserRole.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class InforUser {
/*
{
  "id": 22,
  "firstName": "string",
  "lastName": "string",
  "nickName": "Kamen Rider",
  "email": "string",
  "avatar": "string",
  "phone": "0865901935",
  "date": "2001-03-30",
  "role": [
    {
      "id": 2,
      "name": "USER"
    }
  ],
  "createdAt": "2023-11-08T16:28:05.858",
  "status": "ACTIVE"
}
*/

  int? id;
  String? firstName;
  String? lastName;
  String? nickName;
  String? email;
  String? avatar;
  String? phone;
  String? date;
  List<InforUserRole?>? role;
  String? createdAt;
  String? status;

  InforUser({
    this.id,
    this.firstName,
    this.lastName,
    this.nickName,
    this.email,
    this.avatar,
    this.phone,
    this.date,
    this.role,
    this.createdAt,
    this.status,
  });
  InforUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    nickName = json['nickName']?.toString();
    email = json['email']?.toString();
    avatar = json['avatar']?.toString();
    phone = json['phone']?.toString();
    date = json['date']?.toString();
    if (json['role'] != null) {
      final v = json['role'];
      final arr0 = <InforUserRole>[];
      v.forEach((v) {
        arr0.add(InforUserRole.fromJson(v));
      });
      role = arr0;
    }
    createdAt = json['createdAt']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['nickName'] = nickName;
    data['email'] = email;
    data['avatar'] = avatar;
    data['phone'] = phone;
    data['date'] = date;
    if (role != null) {
      final v = role;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['role'] = arr0;
    }
    data['createdAt'] = createdAt;
    data['status'] = status;
    return data;
  }
}
