///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DiaryUserModel {
/*
{
  "id": 17,
  "title": "string",
  "happened": "string",
  "thinkingMoment": "string",
  "time": "2023-11-08T09:18:10.149",
  "place": "string",
  "thinkingNow": "string",
  "thinkingFelt": "string",
  "change": "string",
  "other": "string",
  "createdAt": "2023-11-08T16:18:38.502",
  "createdBy": 1,
  "nickname": "mohamed Salah",
  "avatar": "string",
  "status": "PUBLIC"
}
*/

  int? id;
  String? title;
  String? happened;
  String? thinkingMoment;
  String? time;
  String? place;
  String? thinkingNow;
  String? thinkingFelt;
  String? change;
  String? other;
  String? createdAt;
  int? createdBy;
  String? nickname;
  String? avatar;
  String? status;

  DiaryUserModel({
    this.id,
    this.title,
    this.happened,
    this.thinkingMoment,
    this.time,
    this.place,
    this.thinkingNow,
    this.thinkingFelt,
    this.change,
    this.other,
    this.createdAt,
    this.createdBy,
    this.nickname,
    this.avatar,
    this.status,
  });
  DiaryUserModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    happened = json['happened']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    time = json['time']?.toString();
    place = json['place']?.toString();
    thinkingNow = json['thinkingNow']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    change = json['change']?.toString();
    other = json['other']?.toString();
    createdAt = json['createdAt']?.toString();
    createdBy = json['createdBy']?.toInt();
    nickname = json['nickname']?.toString();
    avatar = json['avatar']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['happened'] = happened;
    data['thinkingMoment'] = thinkingMoment;
    data['time'] = time;
    data['place'] = place;
    data['thinkingNow'] = thinkingNow;
    data['thinkingFelt'] = thinkingFelt;
    data['change'] = change;
    data['other'] = other;
    data['createdAt'] = createdAt;
    data['createdBy'] = createdBy;
    data['nickname'] = nickname;
    data['avatar'] = avatar;
    data['status'] = status;
    return data;
  }
}
