///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DiaryUserModel {
/*
{
  "id": 18,
  "title": "string",
  "mood": "tức giận",
  "happened": "Bây giờ em biết vì sao gặp nhau biển xô sóng trào.Ngồi nghe chiều im gió lặng giữa muôn vàn hoa.Đi về đâu cũng là thế, buồn kia còn trong dáng ngồi.Thiên đường xưa khép lại……. từ muôn năm rồi",
  "thinkingMoment": "string",
  "time": "2023-11-08T09:29:00.778",
  "place": "string",
  "thinkingNow": "yêu đời",
  "thinkingFelt": "string",
  "change": "string",
  "other": "string",
  "status": "PUBLIC",
  "createdBy": "22",
  "createdAt": "2023-11-08T16:31:52.184",
  "nickname": "Kamen Rider",
  "avatar": "string"
}
*/

  int? id;
  String? title;
  String? mood;
  String? happened;
  String? thinkingMoment;
  String? time;
  String? place;
  String? thinkingNow;
  String? thinkingFelt;
  String? change;
  String? other;
  String? status;
  String? createdBy;
  String? createdAt;
  String? nickname;
  String? avatar;

  DiaryUserModel({
    this.id,
    this.title,
    this.mood,
    this.happened,
    this.thinkingMoment,
    this.time,
    this.place,
    this.thinkingNow,
    this.thinkingFelt,
    this.change,
    this.other,
    this.status,
    this.createdBy,
    this.createdAt,
    this.nickname,
    this.avatar,
  });
  DiaryUserModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    mood = json['mood']?.toString();
    happened = json['happened']?.toString();
    thinkingMoment = json['thinkingMoment']?.toString();
    time = json['time']?.toString();
    place = json['place']?.toString();
    thinkingNow = json['thinkingNow']?.toString();
    thinkingFelt = json['thinkingFelt']?.toString();
    change = json['change']?.toString();
    other = json['other']?.toString();
    status = json['status']?.toString();
    createdBy = json['createdBy']?.toString();
    createdAt = json['createdAt']?.toString();
    nickname = json['nickname']?.toString();
    avatar = json['avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['mood'] = mood;
    data['happened'] = happened;
    data['thinkingMoment'] = thinkingMoment;
    data['time'] = time;
    data['place'] = place;
    data['thinkingNow'] = thinkingNow;
    data['thinkingFelt'] = thinkingFelt;
    data['change'] = change;
    data['other'] = other;
    data['status'] = status;
    data['createdBy'] = createdBy;
    data['createdAt'] = createdAt;
    data['nickname'] = nickname;
    data['avatar'] = avatar;
    return data;
  }
}
